name: PlayerDataPlugin
version: '1.2.1'
main: de.heiligekiwi.playerdata.PlayerDataPlugin
api-version: '1.21'
load: STARTUP
authors:
  - HeiligeKiwi
description: A plugin to manage player data, including IP addresses, notes, and whitelist status.

# Dependencies
depend:
  - LuckPerms
softdepend:
  - Vault

commands:
  playerip:
    description: Get the IP address of a player.
    permission: nationfight.playerdata.playerip
  note:
    description: Manage player notes.
    permission: nationfight.playerdata.note
  pdp:
    description: Manage IP history and join our Discord.
    permission: nationfight.playerdata.pdp

permissions:
  nationfight.playerdata.playerip:
    description: Permission to use the /playerip command.
    default: op
  nationfight.playerdata.note:
    description: Permission to manage player notes.
    default: op
  nationfight.playerdata.ipchange:
    description: Permission to receive notifications about IP changes.
    default: op
  nationfight.playerdata.pdp:
    description: Permission to manage IP history and join the Discord.
    default: op